name: build

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Erlang, Gleam, and Rebar3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.7.0"
          rebar3-version: "3"

      # Install Pandoc
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # Download Gleam dependencies
      - run: gleam deps download

      # Run Gleam tests
      - run: gleam test

      # Check formatting
      - run: gleam format --check src test

      # Run `make` to render the README.md file
      - run: make

      # Commit the generated README.md
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "docs(*): [⚙️ ] Built README.md" || true
          git push
